from twilio.rest import Client
from core.config import settings

client = Client(settings.TWILIO_ACCOUNT_SID, settings.TWILIO_AUTH_TOKEN)

def send_visit_summary(patient_phone: str, patient_name: str, report: dict) -> bool:
    """
    Send post-consultation summary to patient via WhatsApp.
    Called after doctor clicks Approve & Finalize.
    """
    
    # Format the message
    drug_warning = ""
    if report.get("drug_interactions"):
        drug_warning = "\n⚠️ *Important:* Your doctor has been alerted about a potential medication interaction. Please follow their guidance carefully.\n"

    followups = report.get("followup_questions", [])
    followup_text = ""
    if followups:
        followup_text = "\n*Things to watch for:*\n" + "\n".join(f"• {q}" for q in followups[:3])

    message = f"""
🏥 *Visit Summary — AIMED*

Hello {patient_name}, here is a summary of your consultation today.

*What you told the doctor:*
{report.get('soap_subjective', 'Not recorded')}

*Your treatment plan:*
{report.get('soap_plan', 'Not recorded')}

{drug_warning}
*In simple words:*
{report.get('plain_language_summary', '')}
{followup_text}

_This summary was generated by AIMED and reviewed by your doctor. Please follow your doctor's advice. For emergencies call 112._
""".strip()

    try:
        client.messages.create(
            from_=settings.TWILIO_WHATSAPP_FROM,
            to=f"whatsapp:+91{patient_phone}",  # assuming Indian numbers
            body=message
        )
        return True
    except Exception as e:
        print(f"[WhatsApp] Failed to send to {patient_phone}: {e}")
        return False
    
if __name__ == "__main__":
    # Test sending a message
    test_report = {
        "soap_subjective": "I have a headache and fever.",
        "soap_plan": "Take paracetamol 500mg twice daily for 5 days.",
        "plain_language_summary": "You have a headache and fever. Take paracetamol as prescribed.",
        "drug_interactions": True,
        "followup_questions": ["Monitor your temperature", "Stay hydrated", "Rest well"]
    }
    send_visit_summary("7217786772", "Rakshit Sawarn", test_report)